from pptx import Presentation
from pptx.util import Inches, Pt, Emu
from pptx.dml.color import RGBColor
from pptx.enum.text import PP_ALIGN
from datetime import datetime
import re


# ─── DESIGN TOKENS ────────────────────────────────────────────────────────────
DARK_BLUE = RGBColor(0x1F, 0x36, 0x64)
MID_BLUE  = RGBColor(0x2E, 0x75, 0xB6)
LIGHT_BLUE= RGBColor(0xBD, 0xD7, 0xEE)
WHITE     = RGBColor(0xFF, 0xFF, 0xFF)
DARK_GRAY = RGBColor(0x40, 0x40, 0x40)
LIGHT_GRAY= RGBColor(0xF2, 0xF2, 0xF2)


def _set_bg(slide, color: RGBColor):
    fill = slide.background.fill
    fill.solid()
    fill.fore_color.rgb = color


def _add_textbox(slide, text, left, top, width, height,
                 font_size=14, bold=False, color=WHITE,
                 align=PP_ALIGN.LEFT, wrap=True):
    txBox = slide.shapes.add_textbox(
        Inches(left), Inches(top), Inches(width), Inches(height)
    )
    txBox.word_wrap = wrap
    tf = txBox.text_frame
    tf.word_wrap = wrap
    p = tf.paragraphs[0]
    p.alignment = align
    run = p.add_run()
    run.text = text
    run.font.size = Pt(font_size)
    run.font.bold = bold
    run.font.color.rgb = color
    return txBox


def _add_divider(slide, top, color=MID_BLUE):
    line = slide.shapes.add_shape(
        1,  # MSO_SHAPE_TYPE.RECTANGLE
        Inches(0.5), Inches(top), Inches(9), Inches(0.03)
    )
    line.fill.solid()
    line.fill.fore_color.rgb = color
    line.line.fill.background()


def _extract_section(analysis: str, keywords: list[str], fallback: str = "") -> str:
    """Extract a section from the analysis text by keywords."""
    lines = analysis.split("\n")
    result = []
    capturing = False
    for line in lines:
        if any(kw.lower() in line.lower() for kw in keywords):
            capturing = True
            result = []
            continue
        if capturing:
            if line.startswith("#") and result:
                break
            if line.strip():
                result.append(line.strip().lstrip("*-•").strip())
        if len(result) >= 6:
            break
    return "\n".join(result[:5]) if result else fallback


def generate_pptx(brief: str, analysis: str, output_path: str = "output/report.pptx"):
    """Generate a 6-slide consulting-style PowerPoint from the analysis."""
    prs = Presentation()
    prs.slide_width  = Inches(13.33)
    prs.slide_height = Inches(7.5)

    blank_layout = prs.slide_layouts[6]
    timestamp = datetime.now().strftime("%B %Y")

    # ── SLIDE 1: COVER ────────────────────────────────────────────────────────
    s1 = prs.slides.add_slide(blank_layout)
    _set_bg(s1, DARK_BLUE)

    # Accent bar left
    bar = s1.shapes.add_shape(1, Inches(0), Inches(0), Inches(0.4), Inches(7.5))
    bar.fill.solid(); bar.fill.fore_color.rgb = MID_BLUE; bar.line.fill.background()

    _add_textbox(s1, "MARKET INTELLIGENCE", 0.7, 1.8, 11, 0.6,
                 font_size=13, bold=False, color=LIGHT_BLUE)
    _add_textbox(s1, brief.upper(), 0.7, 2.4, 11, 1.5,
                 font_size=28, bold=True, color=WHITE)
    _add_divider(s1, 4.2, MID_BLUE)
    _add_textbox(s1, f"Market Sizing  •  M&A Landscape  •  GTM Strategy", 0.7, 4.4, 10, 0.5,
                 font_size=12, color=LIGHT_BLUE)
    _add_textbox(s1, timestamp, 0.7, 6.6, 5, 0.4, font_size=11, color=LIGHT_BLUE)
    _add_textbox(s1, "Generated by market-intelligence-agent", 7, 6.6, 5, 0.4,
                 font_size=10, color=RGBColor(0x80, 0x80, 0x80), align=PP_ALIGN.RIGHT)

    # ── SLIDE 2: EXECUTIVE SUMMARY ────────────────────────────────────────────
    s2 = prs.slides.add_slide(blank_layout)
    _set_bg(s2, WHITE)

    header = s2.shapes.add_shape(1, Inches(0), Inches(0), Inches(13.33), Inches(1.2))
    header.fill.solid(); header.fill.fore_color.rgb = DARK_BLUE; header.line.fill.background()

    _add_textbox(s2, "EXECUTIVE SUMMARY", 0.5, 0.25, 10, 0.7,
                 font_size=18, bold=True, color=WHITE)

    summary = _extract_section(analysis,
        ["executive summary", "resumen", "overview", "summary"],
        fallback=analysis[:600])

    _add_textbox(s2, summary, 0.5, 1.5, 12.3, 5.5,
                 font_size=13, color=DARK_GRAY)
    _add_divider(s2, 7.1, LIGHT_BLUE)

    # ── SLIDE 3: MARKET SIZE ──────────────────────────────────────────────────
    s3 = prs.slides.add_slide(blank_layout)
    _set_bg(s3, LIGHT_GRAY)

    header3 = s3.shapes.add_shape(1, Inches(0), Inches(0), Inches(13.33), Inches(1.2))
    header3.fill.solid(); header3.fill.fore_color.rgb = MID_BLUE; header3.line.fill.background()
    _add_textbox(s3, "MARKET SIZING", 0.5, 0.25, 10, 0.7,
                 font_size=18, bold=True, color=WHITE)

    market_text = _extract_section(analysis,
        ["market size", "market sizing", "tam", "total addressable", "tamaño", "mercado"],
        fallback="See full analysis in the Markdown report.")

    _add_textbox(s3, market_text, 0.5, 1.5, 12.3, 5.5,
                 font_size=13, color=DARK_GRAY)

    # ── SLIDE 4: KEY PLAYERS & M&A ────────────────────────────────────────────
    s4 = prs.slides.add_slide(blank_layout)
    _set_bg(s4, WHITE)

    header4 = s4.shapes.add_shape(1, Inches(0), Inches(0), Inches(13.33), Inches(1.2))
    header4.fill.solid(); header4.fill.fore_color.rgb = DARK_BLUE; header4.line.fill.background()
    _add_textbox(s4, "KEY PLAYERS & M&A LANDSCAPE", 0.5, 0.25, 12, 0.7,
                 font_size=18, bold=True, color=WHITE)

    players_text = _extract_section(analysis,
        ["key players", "m&a", "acquisition", "companies", "players", "empresas", "competidores"],
        fallback="See full analysis in the Markdown report.")

    _add_textbox(s4, players_text, 0.5, 1.5, 12.3, 5.5,
                 font_size=13, color=DARK_GRAY)

    # ── SLIDE 5: GTM STRATEGY ─────────────────────────────────────────────────
    s5 = prs.slides.add_slide(blank_layout)
    _set_bg(s5, LIGHT_GRAY)

    header5 = s5.shapes.add_shape(1, Inches(0), Inches(0), Inches(13.33), Inches(1.2))
    header5.fill.solid(); header5.fill.fore_color.rgb = MID_BLUE; header5.line.fill.background()
    _add_textbox(s5, "GO-TO-MARKET STRATEGY", 0.5, 0.25, 10, 0.7,
                 font_size=18, bold=True, color=WHITE)

    gtm_text = _extract_section(analysis,
        ["go-to-market", "gtm", "entry", "strategy", "estrategia", "entrada", "recomendaciones"],
        fallback="See full analysis in the Markdown report.")

    _add_textbox(s5, gtm_text, 0.5, 1.5, 12.3, 5.5,
                 font_size=13, color=DARK_GRAY)

    # ── SLIDE 6: RECOMMENDATION ───────────────────────────────────────────────
    s6 = prs.slides.add_slide(blank_layout)
    _set_bg(s6, DARK_BLUE)

    bar6 = s6.shapes.add_shape(1, Inches(0), Inches(0), Inches(0.4), Inches(7.5))
    bar6.fill.solid(); bar6.fill.fore_color.rgb = MID_BLUE; bar6.line.fill.background()

    _add_textbox(s6, "STRATEGIC RECOMMENDATION", 0.7, 1.0, 11, 0.7,
                 font_size=18, bold=True, color=LIGHT_BLUE)
    _add_divider(s6, 1.9, MID_BLUE)

    rec_text = _extract_section(analysis,
        ["recommendation", "conclusion", "recomendación", "conclusión", "next steps", "action"],
        fallback="Detailed recommendations available in the full Markdown report.")

    _add_textbox(s6, rec_text, 0.7, 2.1, 12, 4.5,
                 font_size=14, color=WHITE)
    _add_textbox(s6, "market-intelligence-agent  |  github.com/AlexLechado1", 0.7, 6.8, 12, 0.4,
                 font_size=10, color=RGBColor(0x60, 0x60, 0x80), align=PP_ALIGN.RIGHT)

    prs.save(output_path)
    print(f"PowerPoint saved: {output_path}")
    return output_path
