import json
from datetime import datetime


def generate_markdown(brief: str, analysis: str, raw_data: dict, output_path: str = "output/report.md"):
    """Generate a structured Markdown report from the agent's analysis."""
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M")

    sources_used = [k for k, v in raw_data.items() if v and "error" not in str(v)]

    content = f"""# Market Intelligence Report
**Brief:** {brief}
**Generated:** {timestamp}
**Sources:** {", ".join(sources_used) if sources_used else "Multiple public APIs"}

---

{analysis}

---

## Raw Data Summary

```json
{json.dumps({k: v for k, v in raw_data.items() if v}, indent=2, ensure_ascii=False)[:3000]}
```

---
*Generated by market-intelligence-agent using Anthropic Claude + public data APIs*
"""

    with open(output_path, "w", encoding="utf-8") as f:
        f.write(content)

    print(f"Markdown report saved: {output_path}")
    return output_path
